### ISSUE TITLE
http://localhost:3000/graphql

### ISSUE THREAD

**Issue by robbiereynolds** [saikat/react-apollo-starter-kit#10]
Clone Repo -> npm install -> npm run dev

http://localhost:3000 - === works!

http://localhost:3000/graphql -> Apollo Server supports only POST requests.  !== work

Ubuntu 16.04

**Comment by saikat** [comment]
@robbiereynolds The URL to play around with the API is now http://localhost:3000/graphiql.  Try it out now!

**Comment by robbiereynolds** [comment]
Sure enough, that did the trick. Thanks.
