### ISSUE TITLE
LocalCounter.jsx raises error: TypeError: mapState is not a function

### ISSUE THREAD

**Issue by grayontheweb** [saikat/react-apollo-starter-kit#12]
Using this starter kit as a launching point and noticed this issue. Currently `src/containers/LocalCounter.jsx` is exporting a connect function with an object containing the mapStateToProps and mapDispatchToProps functions:

```
export default connect({
  mapStateToProps,
  mapDispatchToProps
})(LocalCounter)
```

This raises a TypeError for me and was fixable by passing two function arguments rather than an object containing them:

```
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(LocalCounter)
```

**Comment by saikat** [comment]
Thanks @grayontheweb -- could you submit a pull request with your fix?

**Comment by grayontheweb** [comment]
Sure, no problem.
