### ISSUE TITLE
port 8080 doesn't work

### ISSUE THREAD

**Issue by KristerV** [saikat/react-apollo-starter-kit#16]
here's what I see when I haven't changed anything and just go to localhost:8080. On Arch linux. Port 3000 seems to work for everything [exept the link](https://github.com/saikat/react-apollo-starter-kit/issues/15). Started with `npm run dev`.

![image](https://cloud.githubusercontent.com/assets/2750622/19973019/9921e318-a1ec-11e6-8405-1ec25095caf0.png)

**Comment by saikat** [comment]
Closing this as the correct port to use is 3000.  8080 is just the backend server but won't load your webpack assets.
