### ISSUE TITLE
Is rollbar messing up your build?

### ISSUE THREAD

**Issue by uiuxguy** [saikat/react-apollo-starter-kit#4]
This is right after first `npm run dev`

<img width="1082" alt="screen shot 2016-08-21 at 11 08 39 am" src="https://cloud.githubusercontent.com/assets/9032594/17839000/4d3653f8-6790-11e6-89ad-4187ea96a4a2.png">

**Comment by vlasenko** [comment]
It's missing `json-loader`. I have submitted PR to fix this: #5 

Meanwhile you can fix this manually:
```
npm install --save-dev json-loader
```

**Comment by saikat** [comment]
This should be fixed now. Closing!
